// generated by TurtleScript write-rust-bytecode.js
use function::Function;
use literal::*;

pub fn init(functions: &mut ~[Function], literals: &mut ~[Literal]) {
  // functions
  vec::push(functions, Function {
    name: None,
    id: 0,
    nargs: 0,
    max_stack: 4,
    bytecode: ~[
      0,	// push_frame
      5, 0,	// get_slot_direct(0)
      15,	// dup
      7, 1,	// get_slot_direct_check(1)
      19,	// swap
      1, 2,	// push_literal(2)
      1, 3,	// push_literal(3)
      10, 2,	// invoke(2)
      14,	// pop
      1, 4,	// push_literal(4)
      11	// return
    ]
  });

  // literals
  vec::push(literals, String(~"console"));	// 0
  vec::push(literals, String(~"log"));	// 1
  vec::push(literals, String(~"Hello,"));	// 2
  vec::push(literals, String(~"world!"));	// 3
  vec::push(literals, Undefined);	// 4
}
